platform :ios, '8.0'
target ‘ToolBox’ do
    pod 'AFNetworking'
    pod 'MJRefresh'
    pod 'SDWebImage'
    pod 'Masonry'
    pod 'SVProgressHUD'
    pod 'IQKeyboardManager'
    pod 'MJExtension'
    pod 'MJRefresh'
    pod 'BRPickerView'
    pod 'Masonry'
  
end

